### PR TITLE
Text search

### PR DESCRIPTION
**Pull request by inaimathi**
Still incomplete; don't merge quite yet

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Looking good!

- I guess that the CLI "serve" command should populate the index, and that we have to reindex (partially?) on changes
- we should be able to clear the search
- we'll need some documentation ([based on this I guess](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html)); I was surprised that "exam" didn't match "Example One", but "exam*" works as expected

**Comment by jamesaoverton** [comment]
Speed is good for ONTIE. I think we should search on keyup.

**Comment by jamesaoverton** [comment]
- Lucene doesn't like forward-slashes, but they're important in ONTIE
- we need to disable auto-everything in the search field: https://davidwalsh.name/disable-autocorrect

I played with this for an hour or so and I really like it.

**Comment by jamesaoverton** [comment]
Ok. Let's just create an index on startup if none exists, and merge what we've got now.

**Comment by inaimathi** [comment]
Managed to fix most of it before your comment above :P The only outstanding thing from that comment volley is the question of what to do about prefix matching (it would be easy enough to add in; I already had to add a saniatation step to support the forward slash behavior).

**Pull request merged**
